name: React App Github Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v3
    - name: Install & build
      env:
        MY_EMAIL: esi.segurity@gmail.com
        MY_NAME: hackanonimous
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        git remote set-url origin https://$MY_NAME:${{secrets.GH_TOKEN}}@github.com/hackanonimous/basic-calc-react.git
        npm install && npm run deploy