name: React App Github Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v3
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      env: 
        MY_USER: hackanonimous
      with:
        registry: ghcr.io
        username: $MY_USER
        password: ${{secrets.GH_TOKEN}}
    - name: Install
      run: npm ci 
    - name: Bundle
      run: npm  run deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branche: main
        folder: dist